### PR TITLE
Add RPM pacakges for systems that do not support DKMS, like Fedora, a…

### PR DESCRIPTION
**Pull request by ChrisHobday**
This pull request adds 2 RPM packages built with AKMOD for systems that do not support DKMS for automatically updating the module when the kernel is updated, like Fedora based systems. I have personally tested them over the last 2 months on Fedora Kinoite, including upgrading from Fedora 39 to 40 and not had any problems. The full RPM build/installation process is documented at https://github.com/ChrisHobday/gcadapter-oc-kmod-rpm.

### CODE REVIEW

**Comment by r-burns** [comment]
Shouldn't these go in the assets of https://github.com/hannesmann/gcadapter-oc-kmod/releases/tag/v1.4? I don't think we should be adding binaries to the git source tree.

**Comment by ChrisHobday** [comment]
These RPMs don't contain any binaries, you can extract them and see one contains the gcadapter_oc.conf file and the other the .spec file and source code for building which is run when the kernel updates. But yeah putting them under releases makes more sense, I'm not sure how or if you can do that with a pull request though.

**Comment by hannesmann** [comment]
Thank you for your contribution, I wanted to get packages for other distros done eventually but never got around to it. I agree with @r-burns that packages don't belong in the source tree. I could either add a link to https://github.com/ChrisHobday/gcadapter-oc-kmod-rpm in the README or the .spec file could be added under `packaging/rpms` and the prebuilt packages in the assets of the latest release.

**Comment by ChrisHobday** [comment]
Alright, sounds like the best option is to add the .spec file to packaging/rpms, update the README to mention it, and add the prebuilt RPMs themselves to the releases. I'll make a separate pull request for the .spec file and README, feel free to grab the RPMs from the https://github.com/ChrisHobday/gcadapter-oc-kmod-rpm releases and add them to the releases here.

**Pull request closed without merging**
